### ISSUE TITLE
Error when running mix deps.get

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/oxleas-adhd#250]
Was getting the following error when trying running the command `mix deps.get`

```
[error] GenServer Hex.Registry.Server terminating
** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
    (hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, :socket_closed_remotely})
    (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
    (hex) lib/hex/registry/server.ex:343: Hex.Registry.Server.write_result/4
    (hex) lib/hex/registry/server.ex:196: Hex.Registry.Server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:get_package, "hexpm", "phoenix_live_reload", {:error, :socket_closed_remotely}}
```

Was able to resolve this by changing wifi networks. Not exactly sure what the problem was

**Comment by RobStallion** [comment]
Was able to resolve this by changing wifi networks. Not exactly sure what the problem was
